number_terms = {
    "1": ["un", "une"],
    "2": ["deux"],
    "3": ["trois"],
    "4": ["quatre"],
    "5": ["cinq"],
    "6": ["six"],
    "7": ["sept"],
    "8": ["huit"],
    "9": ["neuf"],
    "10": ["dix"],
    "11": ["onze"],
    "12": ["douze"],
    "13": ["treize"],
    "14": ["quatorze"],
    "15": ["quinze"],
    "16": ["seize"],
    "17": ["dix-sept", "dix sept"],
    "18": ["dix-huit", "dix huit"],
    "19": ["dix-neuf", "dix neuf"],
    "20": ["vingt", "vingts"],
    "30": ["trente"],
    "40": ["quarante"],
    "50": ["cinquante"],
    "60": ["soixante"],
    "70": ["soixante dix", "soixante-dix"],
    "80": ["quatre vingt", "quatre-vingt", "quatre vingts", "quatre-vingts"],
    "90": ["quatre vingt dix", "quatre-vingt-dix"],
    "100": ["cent"],
    "500": ["cinq cent", "cinq-cent"],
    "1000": ["mille", "milles"],
}


value_range_terms = {
    "<": ["<", "<=", "inferieure a", "inferieur a", "inf a", "inf"],
    ">": [">", ">=", "superieure a", "superieur a", "sup a", "sup"],
}


common_measurements = {
    "eds.weight": {
        "unit": "kg",
        "unitless_patterns": [
            {
                "terms": ["poids", "poid", "pese", "pesant", "pesait", "pesent"],
                "ranges": [
                    {"min": 0, "max": 200, "unit": "kg"},
                    {"min": 200, "unit": "g"},
                ],
            }
        ],
    },
    "eds.size": {
        "unit": "m",
        "unitless_patterns": [
            {
                "terms": [
                    "mesure",
                    "taille",
                    "mesurant",
                    "mesurent",
                    "mesurait",
                    "mesuree",
                    "hauteur",
                    "largeur",
                    "longueur",
                ],
                "ranges": [
                    {"min": 0, "max": 3, "unit": "m"},
                    {"min": 3, "unit": "cm"},
                ],
            }
        ],
    },
    "eds.bmi": {
        "unit": "kg_per_m2",
        "unitless_patterns": [
            {"terms": ["imc", "bmi"], "ranges": [{"unit": "kg_per_m2"}]}
        ],
    },
    "eds.volume": {"unit": "m3", "unitless_patterns": []},
    "eds.bool": {
        "unit": "bool",
        "valueless_patterns": [
            {
                "terms": ["positif", "positifs", "positive", "positives"],
                "measurement": {
                    "value_range": "=",
                    "value": 1,
                    "unit": "bool",
                },
            },
            {
                "terms": ["negatif", "negatifs", "negative", "negatives"],
                "measurement": {
                    "value_range": "=",
                    "value": 0,
                    "unit": "bool",
                },
            },
        ],
    },
}


unit_divisors = ["/", "par"]


stopwords_unitless = ["par", "sur", "de", "a", ":", ",", "et"]


stopwords_measure_unit = ["|", "¦", "…", "."]


units_config = {
    "fm": {
        "scale": 1e-15,
        "terms": ["femtometre", "femtometres", "femto-metre", "femto-metres", "fm"],
        "followed_by": None,
        "ui_decomposition": {"length": 1},
    },
    "pm": {
        "scale": 1e-12,
        "terms": ["picometre", "picometres", "pico-metre", "pico-metres", "pm"],
        "followed_by": None,
        "ui_decomposition": {"length": 1},
    },
    "nm": {
        "scale": 1e-09,
        "terms": ["nanometre", "nanometres", "nano-metre", "nano-metres", "nm"],
        "followed_by": None,
        "ui_decomposition": {"length": 1},
    },
    "μm": {
        "scale": 1e-06,
        "terms": [
            "micrometre",
            "micrometres",
            "micro-metre",
            "micrometres",
            "µm",
            "um",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": 1},
    },
    "mm": {
        "scale": 0.001,
        "terms": ["millimetre", "millimetres", "milimetre", "milimetres", "mm"],
        "followed_by": None,
        "ui_decomposition": {"length": 1},
    },
    "cm": {
        "scale": 0.01,
        "terms": ["centimetre", "centimetres", "cm"],
        "followed_by": None,
        "ui_decomposition": {"length": 1},
    },
    "dm": {
        "scale": 0.1,
        "terms": ["decimetre", "decimetres", "dm"],
        "followed_by": None,
        "ui_decomposition": {"length": 1},
    },
    "m": {
        "scale": 1.0,
        "terms": ["metre", "metres", "m"],
        "followed_by": "cm",
        "ui_decomposition": {"length": 1},
    },
    "dam": {
        "scale": 10.0,
        "terms": ["decametre", "decametres", "dam"],
        "followed_by": None,
        "ui_decomposition": {"length": 1},
    },
    "hm": {
        "scale": 100.0,
        "terms": ["hectometre", "hectometres", "hm"],
        "followed_by": None,
        "ui_decomposition": {"length": 1},
    },
    "km": {
        "scale": 1000.0,
        "terms": ["kilometre", "kilometres", "km"],
        "followed_by": "m",
        "ui_decomposition": {"length": 1},
    },
    "fg": {
        "scale": 1e-18,
        "terms": [
            "femtogramme",
            "femtogrammes",
            "femto-gramme",
            "femto-grammes",
            "fgr",
            "fg",
        ],
        "followed_by": None,
        "ui_decomposition": {"mass": 1},
    },
    "pg": {
        "scale": 1e-15,
        "terms": [
            "picogramme",
            "picogrammes",
            "pico-gramme",
            "pico-grammes",
            "pgr",
            "pg",
        ],
        "followed_by": None,
        "ui_decomposition": {"mass": 1},
    },
    "ng": {
        "scale": 1e-12,
        "terms": [
            "nanogramme",
            "nanogrammes",
            "nano-gramme",
            "nano-grammes",
            "ngr",
            "ng",
        ],
        "followed_by": None,
        "ui_decomposition": {"mass": 1},
    },
    "µg": {
        "scale": 1e-9,
        "terms": [
            "microgramme",
            "microgrammes",
            "micro-gramme",
            "micro-grammes",
            "µgr",
            "µg",
            "ugr",
            "ug",
        ],
        "followed_by": None,
        "ui_decomposition": {"mass": 1},
    },
    "mg": {
        "scale": 1e-6,
        "terms": [
            "milligramme",
            "miligramme",
            "milligrammes",
            "miligrammes",
            "mgr",
            "mg",
        ],
        "followed_by": None,
        "ui_decomposition": {"mass": 1},
    },
    "cg": {
        "scale": 1e-5,
        "terms": ["centigramme", "centigrammes", "cg", "cgr"],
        "followed_by": None,
        "ui_decomposition": {"mass": 1},
    },
    "dg": {
        "scale": 1e-4,
        "terms": ["decigramme", "decigrammes", "dgr", "dg"],
        "followed_by": None,
        "ui_decomposition": {"mass": 1},
    },
    "g": {
        "scale": 0.001,
        "terms": ["gramme", "grammes", "gr", "g"],
        "followed_by": None,
        "ui_decomposition": {"mass": 1},
    },
    "dag": {
        "scale": 0.01,
        "terms": ["decagramme", "decagrammes", "dagr", "dag"],
        "followed_by": None,
        "ui_decomposition": {"mass": 1},
    },
    "hg": {
        "scale": 0.1,
        "terms": ["hectogramme", "hectogrammes", "hgr", "hg"],
        "followed_by": None,
        "ui_decomposition": {"mass": 1},
    },
    "kg": {
        "scale": 1.0,
        "terms": ["kilo", "kilogramme", "kilogrammes", "kgr", "kg"],
        "followed_by": "g",
        "ui_decomposition": {"mass": 1},
    },
    "fs": {
        "scale": 1e-15,
        "terms": [
            "femtoseconde",
            "femtosecondes",
            "femto-seconde",
            "femto-secondes",
            "fs",
        ],
        "followed_by": None,
        "ui_decomposition": {"time": 1},
    },
    "ps": {
        "scale": 1e-12,
        "terms": ["picoseconde", "picosecondes", "pico-seconde", "pico-secondes", "ps"],
        "followed_by": None,
        "ui_decomposition": {"time": 1},
    },
    "ns": {
        "scale": 1e-09,
        "terms": ["nanoseconde", "nanosecondes", "nano-seconde", "nano-secondes", "ns"],
        "followed_by": None,
        "ui_decomposition": {"time": 1},
    },
    "µs": {
        "scale": 1e-06,
        "terms": [
            "microseconde",
            "microsecondes",
            "micro-seconde",
            "micro-secondes",
            "µs",
            "us",
        ],
        "followed_by": None,
        "ui_decomposition": {"time": 1},
    },
    "ms": {
        "scale": 0.001,
        "terms": ["milliseconde", "millisecondes", "miliseconde", "milisecondes", "ms"],
        "followed_by": None,
        "ui_decomposition": {"time": 1},
    },
    "s": {
        "scale": 1,
        "terms": ["seconde", "secondes", "s"],
        "followed_by": None,
        "ui_decomposition": {"time": 1},
    },
    "min": {
        "scale": 60,
        "terms": ["mn", "min", "minute", "minutes"],
        "followed_by": "second",
        "ui_decomposition": {"time": 1},
    },
    "h": {
        "scale": 3600,
        "terms": ["heure", "heures", "h"],
        "followed_by": "minute",
        "ui_decomposition": {"time": 1},
    },
    "day": {
        "scale": 3600,
        "terms": ["jour", "jours", "j"],
        "followed_by": None,
        "ui_decomposition": {"time": 1},
    },
    "month": {
        "scale": 109500.12,
        "terms": ["mois"],
        "followed_by": None,
        "ui_decomposition": {"time": 1},
    },
    "week": {
        "scale": 25200,
        "terms": ["semaine", "semaines"],
        "followed_by": None,
        "ui_decomposition": {"time": 1},
    },
    "year": {
        "scale": 1314900.0,
        "terms": ["an", "année", "ans", "années"],
        "followed_by": None,
        "ui_decomposition": {"time": 1},
    },
    "arc-second": {
        "scale": 0.03333333333333333,
        "terms": ['"', "''"],
        "followed_by": None,
        "ui_decomposition": {"time": 1},
    },
    "arc-minute": {
        "scale": 2,
        "terms": ["'"],
        "followed_by": "arc-second",
        "ui_decomposition": {"time": 1},
    },
    "degree": {
        "scale": 120,
        "terms": ["degre", "°", "deg"],
        "followed_by": "arc-minute",
        "ui_decomposition": {"time": 1},
    },
    "celcius": {
        "scale": 1,
        "terms": ["°C", "° celcius", "celcius"],
        "followed_by": None,
        "ui_decomposition": {"temperature": 1},
    },
    "fl": {
        "scale": 1e-18,
        "terms": ["femtolitre", "femtolitres", "femto-litre", "femto-litres", "fl"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "pl": {
        "scale": 1e-15,
        "terms": ["picolitre", "picolitres", "pico-litre", "pico-litres", "pl"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "nl": {
        "scale": 1e-12,
        "terms": ["nanolitre", "nanolitres", "nano-litre", "nano-litres", "nl"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "µl": {
        "scale": 1e-09,
        "terms": [
            "microlitre",
            "microlitres",
            "micro-litre",
            "micro-litres",
            "µl",
            "ul",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "ml": {
        "scale": 1e-06,
        "terms": ["mililitre", "millilitre", "mililitres", "millilitres", "ml"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "cl": {
        "scale": 1e-05,
        "terms": ["centilitre", "centilitres", "cl"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "dl": {
        "scale": 0.0001,
        "terms": ["decilitre", "decilitres", "dl"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "l": {
        "scale": 0.001,
        "terms": ["litre", "litres", "l"],
        "followed_by": "ml",
        "ui_decomposition": {"length": 3},
    },
    "dal": {
        "scale": 0.01,
        "terms": ["decalitre", "decalitres", "dal"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "hl": {
        "scale": 0.1,
        "terms": ["hectolitre", "hectolitres", "hl"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "kl": {
        "scale": 1.0,
        "terms": ["kilolitre", "kilolitres", "kl"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "cac": {
        "scale": 5e-09,
        "terms": ["cac", "c.a.c", "cuillere à café", "cuillères à café"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "goutte": {
        "scale": 5e-11,
        "terms": ["gt", "goutte"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "fm3": {
        "scale": 1e-45,
        "terms": ["fm3", "fm³"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "pm3": {
        "scale": 1e-36,
        "terms": ["pm3", "pm³"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "nm3": {
        "scale": 1e-27,
        "terms": ["nm3", "nm³"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "µm3": {
        "scale": 1e-18,
        "terms": ["um3", "um³", "µm3", "µm³"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "mm3": {
        "scale": 1e-09,
        "terms": ["mm3", "mm³"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "cm3": {
        "scale": 1e-06,
        "terms": ["cm3", "cm³", "cc"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "dm3": {
        "scale": 0.001,
        "terms": ["dm3", "dm³"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "m3": {
        "scale": 1,
        "terms": ["m3", "m³"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "dam3": {
        "scale": 1000.0,
        "terms": ["dam3", "dam³"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "hm3": {
        "scale": 1000000.0,
        "terms": ["hm3", "hm³"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "km3": {
        "scale": 1000000000.0,
        "terms": ["km3", "km³"],
        "followed_by": None,
        "ui_decomposition": {"length": 3},
    },
    "fm2": {
        "scale": 1e-30,
        "terms": ["fm2", "fm²"],
        "followed_by": None,
        "ui_decomposition": {"length": 2},
    },
    "pm2": {
        "scale": 1e-24,
        "terms": ["fm2", "fm²"],
        "followed_by": None,
        "ui_decomposition": {"length": 2},
    },
    "nm2": {
        "scale": 1e-18,
        "terms": ["nm2", "nm²"],
        "followed_by": None,
        "ui_decomposition": {"length": 2},
    },
    "μm2": {
        "scale": 1e-12,
        "terms": ["µm2", "µm²", "um2", "um²"],
        "followed_by": None,
        "ui_decomposition": {"length": 2},
    },
    "mm2": {
        "scale": 1e-06,
        "terms": ["mm2", "mm²"],
        "followed_by": None,
        "ui_decomposition": {"length": 2},
    },
    "cm2": {
        "scale": 0.0001,
        "terms": ["cm2", "cm²"],
        "followed_by": None,
        "ui_decomposition": {"length": 2},
    },
    "dm2": {
        "scale": 0.01,
        "terms": ["dm2", "dm²"],
        "followed_by": None,
        "ui_decomposition": {"length": 2},
    },
    "m2": {
        "scale": 1.0,
        "terms": ["m2", "m²"],
        "followed_by": None,
        "ui_decomposition": {"length": 2},
    },
    "dam2": {
        "scale": 100.0,
        "terms": ["dam2", "dam²"],
        "followed_by": None,
        "ui_decomposition": {"length": 2},
    },
    "hm2": {
        "scale": 10000.0,
        "terms": ["hm2", "hm²"],
        "followed_by": None,
        "ui_decomposition": {"length": 2},
    },
    "km2": {
        "scale": 1000000.0,
        "terms": ["km2", "km²"],
        "followed_by": None,
        "ui_decomposition": {"length": 2},
    },
    "fui": {
        "scale": 1e-15,
        "terms": ["fui", "f ui", "fu", "f u"],
        "followed_by": None,
        "ui_decomposition": {"ui": 1},
    },
    "pui": {
        "scale": 1e-12,
        "terms": ["pui", "p ui", "pu", "p u"],
        "followed_by": None,
        "ui_decomposition": {"ui": 1},
    },
    "nui": {
        "scale": 1e-09,
        "terms": ["nui", "n ui", "nu", "n u"],
        "followed_by": None,
        "ui_decomposition": {"ui": 1},
    },
    "µui": {
        "scale": 1e-06,
        "terms": ["µui", "µ ui", "uui", "u ui", "µu", "µ u", "uu", "u u"],
        "followed_by": None,
        "ui_decomposition": {"ui": 1},
    },
    "mui": {
        "scale": 0.001,
        "terms": ["mui", "m ui", "mu", "m u"],
        "followed_by": None,
        "ui_decomposition": {"ui": 1},
    },
    "cui": {
        "scale": 0.01,
        "terms": ["cui", "c ui", "cu", "c u"],
        "followed_by": None,
        "ui_decomposition": {"ui": 1},
    },
    "dui": {
        "scale": 0.1,
        "terms": ["dui", "d ui", "du", "d u"],
        "followed_by": None,
        "ui_decomposition": {"ui": 1},
    },
    "ui": {
        "scale": 1.0,
        "terms": ["ui", "u"],
        "followed_by": None,
        "ui_decomposition": {"ui": 1},
    },
    "daui": {
        "scale": 10.0,
        "terms": ["daui", "dau"],
        "followed_by": None,
        "ui_decomposition": {"ui": 1},
    },
    "hui": {
        "scale": 100.0,
        "terms": ["hui", "hu"],
        "followed_by": None,
        "ui_decomposition": {"ui": 1},
    },
    "kui": {
        "scale": 1000.0,
        "terms": ["kui", "ku"],
        "followed_by": None,
        "ui_decomposition": {"ui": 1},
    },
    "fmol": {
        "scale": 1e-15,
        "terms": ["fmol", "f mol", "fmole", "f mole"],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": 1},
    },
    "pmol": {
        "scale": 1e-12,
        "terms": ["pmol", "p mol", "pmole", "p mole"],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": 1},
    },
    "nmol": {
        "scale": 1e-09,
        "terms": ["nmol", "n mol", "nmole", "n mole"],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": 1},
    },
    "µmol": {
        "scale": 1e-06,
        "terms": ["µmol", "µ mol", "umole", "u mole"],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": 1},
    },
    "mmol": {
        "scale": 0.001,
        "terms": ["mmol", "m mol", "mmole", "m mole"],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": 1},
    },
    "cmol": {
        "scale": 0.01,
        "terms": ["cmol", "c mol", "cmole", "c mole"],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": 1},
    },
    "dmol": {
        "scale": 0.1,
        "terms": ["dmol", "d mol", "dmole", "d mole"],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": 1},
    },
    "mol": {
        "scale": 1.0,
        "terms": ["mol", "mole"],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": 1},
    },
    "damol": {
        "scale": 10.0,
        "terms": ["damol", "da mol", "damole", "da mole"],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": 1},
    },
    "hmol": {
        "scale": 100.0,
        "terms": ["hmol", "h mol", "hmole", "h mole"],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": 1},
    },
    "kmol": {
        "scale": 1000.0,
        "terms": ["kmol", "k mol", "kmole", "k mole"],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": 1},
    },
    "per_fm": {
        "scale": 1.0e15,
        "terms": [
            "/femtometre",
            "femtometre⁻¹",
            "femtometre-1",
            "/femtometres",
            "femtometres⁻¹",
            "femtometres-1",
            "/femto-metre",
            "femto-metre⁻¹",
            "femto-metre-1",
            "/femto-metres",
            "femto-metres⁻¹",
            "femto-metres-1",
            "/fm",
            "fm⁻¹",
            "fm-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -1},
    },
    "per_pm": {
        "scale": 1.0e12,
        "terms": [
            "/picometre",
            "picometre⁻¹",
            "picometre-1",
            "/picometres",
            "picometres⁻¹",
            "picometres-1",
            "/pico-metre",
            "pico-metre⁻¹",
            "pico-metre-1",
            "/pico-metres",
            "pico-metres⁻¹",
            "pico-metres-1",
            "/pm",
            "pm⁻¹",
            "pm-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -1},
    },
    "per_nm": {
        "scale": 1.0e9,
        "terms": [
            "/nanometre",
            "nanometre⁻¹",
            "nanometre-1",
            "/nanometres",
            "nanometres⁻¹",
            "nanometres-1",
            "/nano-metre",
            "nano-metre⁻¹",
            "nano-metre-1",
            "/nano-metres",
            "nano-metres⁻¹",
            "nano-metres-1",
            "/nm",
            "nm⁻¹",
            "nm-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -1},
    },
    "per_μm": {
        "scale": 1.0e6,
        "terms": [
            "/micrometre",
            "micrometre⁻¹",
            "micrometre-1",
            "/micrometres",
            "micrometres⁻¹",
            "micrometres-1",
            "/micro-metre",
            "micro-metre⁻¹",
            "micro-metre-1",
            "/micrometres",
            "micrometres⁻¹",
            "micrometres-1",
            "/µm",
            "µm⁻¹",
            "µm-1",
            "/um",
            "um⁻¹",
            "um-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -1},
    },
    "per_mm": {
        "scale": 1000.0,
        "terms": [
            "/millimetre",
            "millimetre⁻¹",
            "millimetre-1",
            "/millimetres",
            "millimetres⁻¹",
            "millimetres-1",
            "/milimetre",
            "milimetre⁻¹",
            "milimetre-1",
            "/milimetres",
            "milimetres⁻¹",
            "milimetres-1",
            "/mm",
            "mm⁻¹",
            "mm-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -1},
    },
    "per_cm": {
        "scale": 100.0,
        "terms": [
            "/centimetre",
            "centimetre⁻¹",
            "centimetre-1",
            "/centimetres",
            "centimetres⁻¹",
            "centimetres-1",
            "/cm",
            "cm⁻¹",
            "cm-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -1},
    },
    "per_dm": {
        "scale": 10.0,
        "terms": [
            "/decimetre",
            "decimetre⁻¹",
            "decimetre-1",
            "/decimetres",
            "decimetres⁻¹",
            "decimetres-1",
            "/dm",
            "dm⁻¹",
            "dm-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -1},
    },
    "per_m": {
        "scale": 1.0,
        "terms": [
            "/metre",
            "metre⁻¹",
            "metre-1",
            "/metres",
            "metres⁻¹",
            "metres-1",
            "/m",
            "m⁻¹",
            "m-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -1},
    },
    "per_dam": {
        "scale": 0.1,
        "terms": [
            "/decametre",
            "decametre⁻¹",
            "decametre-1",
            "/decametres",
            "decametres⁻¹",
            "decametres-1",
            "/dam",
            "dam⁻¹",
            "dam-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -1},
    },
    "per_hm": {
        "scale": 0.01,
        "terms": [
            "/hectometre",
            "hectometre⁻¹",
            "hectometre-1",
            "/hectometres",
            "hectometres⁻¹",
            "hectometres-1",
            "/hm",
            "hm⁻¹",
            "hm-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -1},
    },
    "per_km": {
        "scale": 0.001,
        "terms": [
            "/kilometre",
            "kilometre⁻¹",
            "kilometre-1",
            "/kilometres",
            "kilometres⁻¹",
            "kilometres-1",
            "/km",
            "km⁻¹",
            "km-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -1},
    },
    "per_fg": {
        "scale": 1.0e18,
        "terms": [
            "/femtogramme",
            "femtogramme⁻¹",
            "femtogramme-1",
            "/femtogrammes",
            "femtogrammes⁻¹",
            "femtogrammes-1",
            "/femto-gramme",
            "femto-gramme⁻¹",
            "femto-gramme-1",
            "/femto-grammes",
            "femto-grammes⁻¹",
            "femto-grammes-1",
            "/fgr",
            "fgr⁻¹",
            "fgr-1",
            "/fg",
            "fg⁻¹",
            "fg-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"mass": -1},
    },
    "per_pg": {
        "scale": 1.0e15,
        "terms": [
            "/picogramme",
            "picogramme⁻¹",
            "picogramme-1",
            "/picogrammes",
            "picogrammes⁻¹",
            "picogrammes-1",
            "/pico-gramme",
            "pico-gramme⁻¹",
            "pico-gramme-1",
            "/pico-grammes",
            "pico-grammes⁻¹",
            "pico-grammes-1",
            "/pgr",
            "pgr⁻¹",
            "pgr-1",
            "/pg",
            "pg⁻¹",
            "pg-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"mass": -1},
    },
    "per_ng": {
        "scale": 1.0e12,
        "terms": [
            "/nanogramme",
            "nanogramme⁻¹",
            "nanogramme-1",
            "/nanogrammes",
            "nanogrammes⁻¹",
            "nanogrammes-1",
            "/nano-gramme",
            "nano-gramme⁻¹",
            "nano-gramme-1",
            "/nano-grammes",
            "nano-grammes⁻¹",
            "nano-grammes-1",
            "/ngr",
            "ngr⁻¹",
            "ngr-1",
            "/ng",
            "ng⁻¹",
            "ng-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"mass": -1},
    },
    "per_µg": {
        "scale": 1.0e9,
        "terms": [
            "/microgramme",
            "microgramme⁻¹",
            "microgramme-1",
            "/microgrammes",
            "microgrammes⁻¹",
            "microgrammes-1",
            "/micro-gramme",
            "micro-gramme⁻¹",
            "micro-gramme-1",
            "/micro-grammes",
            "micro-grammes⁻¹",
            "micro-grammes-1",
            "/µgr",
            "µgr⁻¹",
            "µgr-1",
            "/µg",
            "µg⁻¹",
            "µg-1",
            "/ugr",
            "ugr⁻¹",
            "ugr-1",
            "/ug",
            "ug⁻¹",
            "ug-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"mass": -1},
    },
    "per_mg": {
        "scale": 1.0e6,
        "terms": [
            "/milligramme",
            "milligramme⁻¹",
            "milligramme-1",
            "/miligramme",
            "miligramme⁻¹",
            "miligramme-1",
            "/milligrammes",
            "milligrammes⁻¹",
            "milligrammes-1",
            "/miligrammes",
            "miligrammes⁻¹",
            "miligrammes-1",
            "/mgr",
            "mgr⁻¹",
            "mgr-1",
            "/mg",
            "mg⁻¹",
            "mg-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"mass": -1},
    },
    "per_cg": {
        "scale": 1.0e5,
        "terms": [
            "/centigramme",
            "centigramme⁻¹",
            "centigramme-1",
            "/centigrammes",
            "centigrammes⁻¹",
            "centigrammes-1",
            "/cg",
            "cg⁻¹",
            "cg-1",
            "/cgr",
            "cgr⁻¹",
            "cgr-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"mass": -1},
    },
    "per_dg": {
        "scale": 1.0e4,
        "terms": [
            "/decigramme",
            "decigramme⁻¹",
            "decigramme-1",
            "/decigrammes",
            "decigrammes⁻¹",
            "decigrammes-1",
            "/dgr",
            "dgr⁻¹",
            "dgr-1",
            "/dg",
            "dg⁻¹",
            "dg-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"mass": -1},
    },
    "per_g": {
        "scale": 1000.0,
        "terms": [
            "/gramme",
            "gramme⁻¹",
            "gramme-1",
            "/grammes",
            "grammes⁻¹",
            "grammes-1",
            "/gr",
            "gr⁻¹",
            "gr-1",
            "/g",
            "g⁻¹",
            "g-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"mass": -1},
    },
    "per_dag": {
        "scale": 100.0,
        "terms": [
            "/decagramme",
            "decagramme⁻¹",
            "decagramme-1",
            "/decagrammes",
            "decagrammes⁻¹",
            "decagrammes-1",
            "/dagr",
            "dagr⁻¹",
            "dagr-1",
            "/dag",
            "dag⁻¹",
            "dag-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"mass": -1},
    },
    "per_hg": {
        "scale": 10.0,
        "terms": [
            "/hectogramme",
            "hectogramme⁻¹",
            "hectogramme-1",
            "/hectogrammes",
            "hectogrammes⁻¹",
            "hectogrammes-1",
            "/hgr",
            "hgr⁻¹",
            "hgr-1",
            "/hg",
            "hg⁻¹",
            "hg-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"mass": -1},
    },
    "per_kg": {
        "scale": 1.0,
        "terms": [
            "/kilo",
            "kilo⁻¹",
            "kilo-1",
            "/kilogramme",
            "kilogramme⁻¹",
            "kilogramme-1",
            "/kilogrammes",
            "kilogrammes⁻¹",
            "kilogrammes-1",
            "/kgr",
            "kgr⁻¹",
            "kgr-1",
            "/kg",
            "kg⁻¹",
            "kg-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"mass": -1},
    },
    "per_fs": {
        "scale": 1.0e15,
        "terms": [
            "/femtoseconde",
            "femtoseconde⁻¹",
            "femtoseconde-1",
            "/femtosecondes",
            "femtosecondes⁻¹",
            "femtosecondes-1",
            "/femto-seconde",
            "femto-seconde⁻¹",
            "femto-seconde-1",
            "/femto-secondes",
            "femto-secondes⁻¹",
            "femto-secondes-1",
            "/fs",
            "fs⁻¹",
            "fs-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"time": -1},
    },
    "per_ps": {
        "scale": 1.0e12,
        "terms": [
            "/picoseconde",
            "picoseconde⁻¹",
            "picoseconde-1",
            "/picosecondes",
            "picosecondes⁻¹",
            "picosecondes-1",
            "/pico-seconde",
            "pico-seconde⁻¹",
            "pico-seconde-1",
            "/pico-secondes",
            "pico-secondes⁻¹",
            "pico-secondes-1",
            "/ps",
            "ps⁻¹",
            "ps-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"time": -1},
    },
    "per_ns": {
        "scale": 1.0e9,
        "terms": [
            "/nanoseconde",
            "nanoseconde⁻¹",
            "nanoseconde-1",
            "/nanosecondes",
            "nanosecondes⁻¹",
            "nanosecondes-1",
            "/nano-seconde",
            "nano-seconde⁻¹",
            "nano-seconde-1",
            "/nano-secondes",
            "nano-secondes⁻¹",
            "nano-secondes-1",
            "/ns",
            "ns⁻¹",
            "ns-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"time": -1},
    },
    "per_µs": {
        "scale": 1.0e6,
        "terms": [
            "/microseconde",
            "microseconde⁻¹",
            "microseconde-1",
            "/microsecondes",
            "microsecondes⁻¹",
            "microsecondes-1",
            "/micro-seconde",
            "micro-seconde⁻¹",
            "micro-seconde-1",
            "/micro-secondes",
            "micro-secondes⁻¹",
            "micro-secondes-1",
            "/µs",
            "µs⁻¹",
            "µs-1",
            "/us",
            "us⁻¹",
            "us-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"time": -1},
    },
    "per_ms": {
        "scale": 1000.0,
        "terms": [
            "/milliseconde",
            "milliseconde⁻¹",
            "milliseconde-1",
            "/millisecondes",
            "millisecondes⁻¹",
            "millisecondes-1",
            "/miliseconde",
            "miliseconde⁻¹",
            "miliseconde-1",
            "/milisecondes",
            "milisecondes⁻¹",
            "milisecondes-1",
            "/ms",
            "ms⁻¹",
            "ms-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"time": -1},
    },
    "per_s": {
        "scale": 1.0,
        "terms": [
            "/seconde",
            "seconde⁻¹",
            "seconde-1",
            "/secondes",
            "secondes⁻¹",
            "secondes-1",
            "/s",
            "s⁻¹",
            "s-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"time": -1},
    },
    "per_min": {
        "scale": 0.016666666666666666,
        "terms": [
            "/mn",
            "mn⁻¹",
            "mn-1",
            "/min",
            "min⁻¹",
            "min-1",
            "/minute",
            "minute⁻¹",
            "minute-1",
            "/minutes",
            "minutes⁻¹",
            "minutes-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"time": -1},
    },
    "per_h": {
        "scale": 0.0002777777777777778,
        "terms": [
            "/heure",
            "heure⁻¹",
            "heure-1",
            "/heures",
            "heures⁻¹",
            "heures-1",
            "/h",
            "h⁻¹",
            "h-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"time": -1},
    },
    "per_day": {
        "scale": 0.0002777777777777778,
        "terms": [
            "/jour",
            "jour⁻¹",
            "jour-1",
            "/jours",
            "jours⁻¹",
            "jours-1",
            "/j",
            "j⁻¹",
            "j-1",
            "/24h",
            "24h⁻¹",
            "24h-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"time": -1},
    },
    "per_month": {
        "scale": 9.132410083203562e-06,
        "terms": ["/mois", "mois⁻¹", "mois-1"],
        "followed_by": None,
        "ui_decomposition": {"time": -1},
    },
    "per_week": {
        "scale": 3.968253968253968e-05,
        "terms": [
            "/semaine",
            "semaine⁻¹",
            "semaine-1",
            "/semaines",
            "semaines⁻¹",
            "semaines-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"time": -1},
    },
    "per_year": {
        "scale": 7.605141075366948e-07,
        "terms": [
            "/an",
            "an⁻¹",
            "an-1",
            "/année",
            "année⁻¹",
            "année-1",
            "/ans",
            "ans⁻¹",
            "ans-1",
            "/années",
            "années⁻¹",
            "années-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"time": -1},
    },
    "per_arc-second": {
        "scale": 30.0,
        "terms": ['/"', '"⁻¹', '"-1', "/''", "''⁻¹", "''-1"],
        "followed_by": None,
        "ui_decomposition": {"time": -1},
    },
    "per_arc-minute": {
        "scale": 0.5,
        "terms": ["/'", "'⁻¹", "'-1"],
        "followed_by": None,
        "ui_decomposition": {"time": -1},
    },
    "per_degree": {
        "scale": 0.008333333333333333,
        "terms": [
            "/degre",
            "degre⁻¹",
            "degre-1",
            "/°",
            "°⁻¹",
            "°-1",
            "/deg",
            "deg⁻¹",
            "deg-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"time": -1},
    },
    "per_celcius": {
        "scale": 1.0,
        "terms": [
            "/°C",
            "°C⁻¹",
            "°C-1",
            "/° celcius",
            "° celcius⁻¹",
            "° celcius-1",
            "/celcius",
            "celcius⁻¹",
            "celcius-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"temperature": -1},
    },
    "per_fl": {
        "scale": 1.0e18,
        "terms": [
            "/femtolitre",
            "femtolitre⁻¹",
            "femtolitre-1",
            "/femtolitres",
            "femtolitres⁻¹",
            "femtolitres-1",
            "/femto-litre",
            "femto-litre⁻¹",
            "femto-litre-1",
            "/femto-litres",
            "femto-litres⁻¹",
            "femto-litres-1",
            "/fl",
            "fl⁻¹",
            "fl-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_pl": {
        "scale": 1.0e15,
        "terms": [
            "/picolitre",
            "picolitre⁻¹",
            "picolitre-1",
            "/picolitres",
            "picolitres⁻¹",
            "picolitres-1",
            "/pico-litre",
            "pico-litre⁻¹",
            "pico-litre-1",
            "/pico-litres",
            "pico-litres⁻¹",
            "pico-litres-1",
            "/pl",
            "pl⁻¹",
            "pl-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_nl": {
        "scale": 1.0e12,
        "terms": [
            "/nanolitre",
            "nanolitre⁻¹",
            "nanolitre-1",
            "/nanolitres",
            "nanolitres⁻¹",
            "nanolitres-1",
            "/nano-litre",
            "nano-litre⁻¹",
            "nano-litre-1",
            "/nano-litres",
            "nano-litres⁻¹",
            "nano-litres-1",
            "/nl",
            "nl⁻¹",
            "nl-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_µl": {
        "scale": 1.0e9,
        "terms": [
            "/microlitre",
            "microlitre⁻¹",
            "microlitre-1",
            "/microlitres",
            "microlitres⁻¹",
            "microlitres-1",
            "/micro-litre",
            "micro-litre⁻¹",
            "micro-litre-1",
            "/micro-litres",
            "micro-litres⁻¹",
            "micro-litres-1",
            "/µl",
            "µl⁻¹",
            "µl-1",
            "/ul",
            "ul⁻¹",
            "ul-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_ml": {
        "scale": 1.0e6,
        "terms": [
            "/mililitre",
            "mililitre⁻¹",
            "mililitre-1",
            "/millilitre",
            "millilitre⁻¹",
            "millilitre-1",
            "/mililitres",
            "mililitres⁻¹",
            "mililitres-1",
            "/millilitres",
            "millilitres⁻¹",
            "millilitres-1",
            "/ml",
            "ml⁻¹",
            "ml-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_cl": {
        "scale": 1.0e5,
        "terms": [
            "/centilitre",
            "centilitre⁻¹",
            "centilitre-1",
            "/centilitres",
            "centilitres⁻¹",
            "centilitres-1",
            "/cl",
            "cl⁻¹",
            "cl-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_dl": {
        "scale": 1.0e4,
        "terms": [
            "/decilitre",
            "decilitre⁻¹",
            "decilitre-1",
            "/decilitres",
            "decilitres⁻¹",
            "decilitres-1",
            "/dl",
            "dl⁻¹",
            "dl-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_l": {
        "scale": 1000.0,
        "terms": [
            "/litre",
            "litre⁻¹",
            "litre-1",
            "/litres",
            "litres⁻¹",
            "litres-1",
            "/l",
            "l⁻¹",
            "l-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_dal": {
        "scale": 100.0,
        "terms": [
            "/decalitre",
            "decalitre⁻¹",
            "decalitre-1",
            "/decalitres",
            "decalitres⁻¹",
            "decalitres-1",
            "/dal",
            "dal⁻¹",
            "dal-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_hl": {
        "scale": 10.0,
        "terms": [
            "/hectolitre",
            "hectolitre⁻¹",
            "hectolitre-1",
            "/hectolitres",
            "hectolitres⁻¹",
            "hectolitres-1",
            "/hl",
            "hl⁻¹",
            "hl-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_kl": {
        "scale": 1.0,
        "terms": [
            "/kilolitre",
            "kilolitre⁻¹",
            "kilolitre-1",
            "/kilolitres",
            "kilolitres⁻¹",
            "kilolitres-1",
            "/kl",
            "kl⁻¹",
            "kl-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_cac": {
        "scale": 200000000.0,
        "terms": [
            "/cac",
            "cac⁻¹",
            "cac-1",
            "/c.a.c",
            "c.a.c⁻¹",
            "c.a.c-1",
            "/cuillere à café",
            "cuillere à café⁻¹",
            "cuillere à café-1",
            "/cuillères à café",
            "cuillères à café⁻¹",
            "cuillères à café-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_goutte": {
        "scale": 20000000000.0,
        "terms": ["/gt", "gt⁻¹", "gt-1", "/goutte", "goutte⁻¹", "goutte-1"],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_fm3": {
        "scale": 1.0e45,
        "terms": [
            "/fm3",
            "fm3⁻¹",
            "fm3-1",
            "/fm³",
            "fm⁻³",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_pm3": {
        "scale": 1.0e36,
        "terms": [
            "/pm3",
            "pm3⁻¹",
            "pm3-1",
            "/pm³",
            "pm⁻³",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_nm3": {
        "scale": 1.0e27,
        "terms": [
            "/nm3",
            "nm3⁻¹",
            "nm3-1",
            "/nm³",
            "nm⁻³",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_µm3": {
        "scale": 1.0e18,
        "terms": [
            "/um3",
            "um3⁻¹",
            "um3-1",
            "/um³",
            "um⁻³",
            "/µm3",
            "µm3⁻¹",
            "µm3-1",
            "/µm³",
            "µm⁻³",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_mm3": {
        "scale": 1.0e9,
        "terms": [
            "/mm3",
            "mm3⁻¹",
            "mm3-1",
            "/mm³",
            "mm⁻³",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_cm3": {
        "scale": 1.0e6,
        "terms": ["/cm3", "cm3⁻¹", "cm3-1", "/cm³", "cm⁻³", "/cc", "cc⁻¹", "cc-1"],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_dm3": {
        "scale": 1000.0,
        "terms": [
            "/dm3",
            "dm3⁻¹",
            "dm3-1",
            "/dm³",
            "dm⁻³",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_m3": {
        "scale": 1.0,
        "terms": [
            "/m3",
            "m3⁻¹",
            "m3-1",
            "/m³",
            "m⁻³",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_dam3": {
        "scale": 0.001,
        "terms": [
            "/dam3",
            "dam3⁻¹",
            "dam3-1",
            "/dam³",
            "dam⁻³",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_hm3": {
        "scale": 1e-06,
        "terms": [
            "/hm3",
            "hm3⁻¹",
            "hm3-1",
            "/hm³",
            "hm⁻³",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_km3": {
        "scale": 1e-09,
        "terms": [
            "/km3",
            "km3⁻¹",
            "km3-1",
            "/km³",
            "km⁻³",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -3},
    },
    "per_fm2": {
        "scale": 1.0 + 30,
        "terms": [
            "/fm2",
            "fm2⁻¹",
            "fm2-1",
            "/fm²",
            "fm⁻²",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -2},
    },
    "per_pm2": {
        "scale": 1.0e24,
        "terms": [
            "/fm2",
            "fm2⁻¹",
            "fm2-1",
            "/fm²",
            "fm⁻²",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -2},
    },
    "per_nm2": {
        "scale": 1.0e18,
        "terms": [
            "/nm2",
            "nm2⁻¹",
            "nm2-1",
            "/nm²",
            "nm⁻²",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -2},
    },
    "per_μm2": {
        "scale": 1.0e12,
        "terms": [
            "/µm2",
            "µm2⁻¹",
            "µm2-1",
            "/µm²",
            "µm⁻²",
            "/um2",
            "um2⁻¹",
            "um2-1",
            "/um²",
            "um⁻²",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -2},
    },
    "per_mm2": {
        "scale": 1.0e6,
        "terms": [
            "/mm2",
            "mm2⁻¹",
            "mm2-1",
            "/mm²",
            "mm⁻²",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -2},
    },
    "per_cm2": {
        "scale": 1.0e4,
        "terms": [
            "/cm2",
            "cm2⁻¹",
            "cm2-1",
            "/cm²",
            "cm⁻²",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -2},
    },
    "per_dm2": {
        "scale": 100.0,
        "terms": [
            "/dm2",
            "dm2⁻¹",
            "dm2-1",
            "/dm²",
            "dm⁻²",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -2},
    },
    "per_m2": {
        "scale": 1.0,
        "terms": [
            "/m2",
            "m2⁻¹",
            "m2-1",
            "/m²",
            "m⁻²",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -2},
    },
    "per_dam2": {
        "scale": 0.01,
        "terms": [
            "/dam2",
            "dam2⁻¹",
            "dam2-1",
            "/dam²",
            "dam⁻²",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -2},
    },
    "per_hm2": {
        "scale": 1.0e-4,
        "terms": [
            "/hm2",
            "hm2⁻¹",
            "hm2-1",
            "/hm²",
            "hm⁻²",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -2},
    },
    "per_km2": {
        "scale": 1e-06,
        "terms": [
            "/km2",
            "km2⁻¹",
            "km2-1",
            "/km²",
            "km⁻²",
        ],
        "followed_by": None,
        "ui_decomposition": {"length": -2},
    },
    "per_fui": {
        "scale": 1.0e15,
        "terms": [
            "/fui",
            "fui⁻¹",
            "fui-1",
            "/f ui",
            "f ui⁻¹",
            "f ui-1",
            "/fu",
            "fu⁻¹",
            "fu-1",
            "/f u",
            "f u⁻¹",
            "f u-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"ui": -1},
    },
    "per_pui": {
        "scale": 1.0e12,
        "terms": [
            "/pui",
            "pui⁻¹",
            "pui-1",
            "/p ui",
            "p ui⁻¹",
            "p ui-1",
            "/pu",
            "pu⁻¹",
            "pu-1",
            "/p u",
            "p u⁻¹",
            "p u-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"ui": -1},
    },
    "per_nui": {
        "scale": 1.0e9,
        "terms": [
            "/nui",
            "nui⁻¹",
            "nui-1",
            "/n ui",
            "n ui⁻¹",
            "n ui-1",
            "/nu",
            "nu⁻¹",
            "nu-1",
            "/n u",
            "n u⁻¹",
            "n u-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"ui": -1},
    },
    "per_µui": {
        "scale": 1.0e6,
        "terms": [
            "/µui",
            "µui⁻¹",
            "µui-1",
            "/µ ui",
            "µ ui⁻¹",
            "µ ui-1",
            "/uui",
            "uui⁻¹",
            "uui-1",
            "/u ui",
            "u ui⁻¹",
            "u ui-1",
            "/µu",
            "µu⁻¹",
            "µu-1",
            "/µ u",
            "µ u⁻¹",
            "µ u-1",
            "/uu",
            "uu⁻¹",
            "uu-1",
            "/u u",
            "u u⁻¹",
            "u u-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"ui": -1},
    },
    "per_mui": {
        "scale": 1000.0,
        "terms": [
            "/mui",
            "mui⁻¹",
            "mui-1",
            "/m ui",
            "m ui⁻¹",
            "m ui-1",
            "/mu",
            "mu⁻¹",
            "mu-1",
            "/m u",
            "m u⁻¹",
            "m u-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"ui": -1},
    },
    "per_cui": {
        "scale": 100.0,
        "terms": [
            "/cui",
            "cui⁻¹",
            "cui-1",
            "/c ui",
            "c ui⁻¹",
            "c ui-1",
            "/cu",
            "cu⁻¹",
            "cu-1",
            "/c u",
            "c u⁻¹",
            "c u-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"ui": -1},
    },
    "per_dui": {
        "scale": 10.0,
        "terms": [
            "/dui",
            "dui⁻¹",
            "dui-1",
            "/d ui",
            "d ui⁻¹",
            "d ui-1",
            "/du",
            "du⁻¹",
            "du-1",
            "/d u",
            "d u⁻¹",
            "d u-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"ui": -1},
    },
    "per_ui": {
        "scale": 1.0,
        "terms": ["/ui", "ui⁻¹", "ui-1", "/u", "u⁻¹", "u-1"],
        "followed_by": None,
        "ui_decomposition": {"ui": -1},
    },
    "per_daui": {
        "scale": 0.1,
        "terms": ["/daui", "daui⁻¹", "daui-1", "/dau", "dau⁻¹", "dau-1"],
        "followed_by": None,
        "ui_decomposition": {"ui": -1},
    },
    "per_hui": {
        "scale": 0.01,
        "terms": ["/hui", "hui⁻¹", "hui-1", "/hu", "hu⁻¹", "hu-1"],
        "followed_by": None,
        "ui_decomposition": {"ui": -1},
    },
    "per_kui": {
        "scale": 0.001,
        "terms": ["/kui", "kui⁻¹", "kui-1", "/ku", "ku⁻¹", "ku-1"],
        "followed_by": None,
        "ui_decomposition": {"ui": -1},
    },
    "per_fmol": {
        "scale": 1.0e15,
        "terms": [
            "/fmol",
            "fmol⁻¹",
            "fmol-1",
            "/f mol",
            "f mol⁻¹",
            "f mol-1",
            "/fmole",
            "fmole⁻¹",
            "fmole-1",
            "/f mole",
            "f mole⁻¹",
            "f mole-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": -1},
    },
    "per_pmol": {
        "scale": 1.0e12,
        "terms": [
            "/pmol",
            "pmol⁻¹",
            "pmol-1",
            "/p mol",
            "p mol⁻¹",
            "p mol-1",
            "/pmole",
            "pmole⁻¹",
            "pmole-1",
            "/p mole",
            "p mole⁻¹",
            "p mole-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": -1},
    },
    "per_nmol": {
        "scale": 1.0e9,
        "terms": [
            "/nmol",
            "nmol⁻¹",
            "nmol-1",
            "/n mol",
            "n mol⁻¹",
            "n mol-1",
            "/nmole",
            "nmole⁻¹",
            "nmole-1",
            "/n mole",
            "n mole⁻¹",
            "n mole-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": -1},
    },
    "per_µmol": {
        "scale": 1.0e6,
        "terms": [
            "/µmol",
            "µmol⁻¹",
            "µmol-1",
            "/µ mol",
            "µ mol⁻¹",
            "µ mol-1",
            "/umole",
            "umole⁻¹",
            "umole-1",
            "/u mole",
            "u mole⁻¹",
            "u mole-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": -1},
    },
    "per_mmol": {
        "scale": 1000.0,
        "terms": [
            "/mmol",
            "mmol⁻¹",
            "mmol-1",
            "/m mol",
            "m mol⁻¹",
            "m mol-1",
            "/mmole",
            "mmole⁻¹",
            "mmole-1",
            "/m mole",
            "m mole⁻¹",
            "m mole-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": -1},
    },
    "per_cmol": {
        "scale": 100.0,
        "terms": [
            "/cmol",
            "cmol⁻¹",
            "cmol-1",
            "/c mol",
            "c mol⁻¹",
            "c mol-1",
            "/cmole",
            "cmole⁻¹",
            "cmole-1",
            "/c mole",
            "c mole⁻¹",
            "c mole-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": -1},
    },
    "per_dmol": {
        "scale": 10.0,
        "terms": [
            "/dmol",
            "dmol⁻¹",
            "dmol-1",
            "/d mol",
            "d mol⁻¹",
            "d mol-1",
            "/dmole",
            "dmole⁻¹",
            "dmole-1",
            "/d mole",
            "d mole⁻¹",
            "d mole-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": -1},
    },
    "per_mol": {
        "scale": 1.0,
        "terms": ["/mol", "mol⁻¹", "mol-1", "/mole", "mole⁻¹", "mole-1"],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": -1},
    },
    "per_damol": {
        "scale": 0.1,
        "terms": [
            "/damol",
            "damol⁻¹",
            "damol-1",
            "/da mol",
            "da mol⁻¹",
            "da mol-1",
            "/damole",
            "damole⁻¹",
            "damole-1",
            "/da mole",
            "da mole⁻¹",
            "da mole-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": -1},
    },
    "per_hmol": {
        "scale": 0.01,
        "terms": [
            "/hmol",
            "hmol⁻¹",
            "hmol-1",
            "/h mol",
            "h mol⁻¹",
            "h mol-1",
            "/hmole",
            "hmole⁻¹",
            "hmole-1",
            "/h mole",
            "h mole⁻¹",
            "h mole-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": -1},
    },
    "per_kmol": {
        "scale": 0.001,
        "terms": [
            "/kmol",
            "kmol⁻¹",
            "kmol-1",
            "/k mol",
            "k mol⁻¹",
            "k mol-1",
            "/kmole",
            "kmole⁻¹",
            "kmole-1",
            "/k mole",
            "k mole⁻¹",
            "k mole-1",
        ],
        "followed_by": None,
        "ui_decomposition": {"nsubstance": -1},
    },
    "nounit": {
        "scale": 1,
        "terms": [],
        "followed_by": None,
        "ui_decomposition": {"nounit": 1},
    },
    "percent": {
        "scale": 0.01,
        "terms": [
            "%",
            "pourcent",
            "pourcents",
        ],
        "followed_by": None,
        "ui_decomposition": {"nounit": 1},
    },
    "permille": {
        "scale": 0.001,
        "terms": [
            "‰",
            "pourmille",
            "pour mille",
            "pourmilles",
            "pour milles",
        ],
        "followed_by": None,
        "ui_decomposition": {"nounit": 1},
    },
    "mmhg": {
        "scale": 133.3224,
        "terms": [
            "mmhg",
            "torr",
        ],
        "followed_by": None,
        "ui_decomposition": {"mass": 1, "length": -1, "time": -2},
    },
    "bool": {
        "scale": 1,
        "terms": [],
        "followed_by": None,
        "ui_decomposition": {"bool": 1},
    },
}

range_patterns = [
    ("De", "à"),
    ("De", "a"),
    ("de", "à"),
    ("de", "a"),
    ("Entre", "et"),
    ("entre", "et"),
    (None, "à"),
]