results_alcohol = dict(
    has_match=[
        True,
        True,
        False,
        False,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        False,
    ],
    detailled_status=[
        None,
        None,
        None,
        None,
        "ABSTINENCE",
        None,
        None,
        "ABSTINENCE",
        None,
        None,
        "ABSTINENCE",
        None,
        None,
    ],
    negation=[
        None,
        None,
        None,
        None,
        None,
        False,
        True,
        None,
        True,
        False,
        False,
        False,
        None,
    ],
    assign=None,
    texts=[
        "Patient alcoolique.",
        "OH chronique.",
        "Prise d'alcool occasionnelle",
        "Application d'un pansement alcoolisé",
        "Présence d'un alcoolisme sevré",
        "Présence d'un alcoolisme non sevré",
        "Alcool: 0",
        "Le patient est en cours de sevrage éthylotabagique",
        "Patient alcoolique: non.",
        "On a un alcoolique non sevré depuis 10 ans.",
        "Alcoolisme sevré",
        "Alcoolisme non sevré",
        "Dosage vitamines 25-OH",
    ],
)
