results_tobacco = dict(
    has_match=[
        True,
        True,
        False,
        True,
        True,
        True,
        True,
        True,
        True,
    ],
    detailled_status=[
        None,
        None,
        None,
        "ABSTINENCE",
        None,
        None,
        "ABSTINENCE",
        None,
        None,
    ],
    negation=[
        None,
        None,
        None,
        None,
        True,
        True,
        None,
        True,
        True,
    ],
    assign=[{"PA": 15}] + 8 * [None],
    texts=[
        "Tabagisme évalué à 15 PA",
        "Patient tabagique",
        "Tabagisme festif",
        "On a un tabagisme ancien",
        "Tabac: 0",
        "Tabagisme passif",
        "Tabac: sevré depuis 5 ans",
        "Le patient ne fume aucun truc.",
        "Le patient fume 0 PA.",
    ],
)
