# This tries to build packages, and tests the packages.
# It runs for release PRs whose source branch follows release/v*.*.* or build-*.
# It makes sure that everything will run when the version is released.

name: Test Build


on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build_wheels:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.head_ref, 'release/v') || startsWith(github.head_ref, 'build-')
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        # 2.4 is too low (can't build for macos, 2.16 is too high (OpenSSL issues)
        uses: pypa/cibuildwheel@v3.3.0
        env:
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ENVIRONMENT: PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cpu PIP_ONLY_BINARY=pyarrow


  build_sdist:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.head_ref, 'release/v') || startsWith(github.head_ref, 'build-')
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build sdist
        run: pipx run build --sdist
